### PR TITLE
Additional busybox options

### PR DESCRIPTION
**Pull request by romracer**
Add tar and gzip support to busybox.  gzip is used to compress the originals.  tar can be deprecated and removed later but I had used it to create some early backups and the uninstaller uses it for now while it provides support for those older backups.

Also add fstab support to mount.  This seems to fix some issues mounting /system in some recoveries but doesn't change binary size.

### CODE REVIEW

**Comment by rovo89** [comment]
Cool, thanks! I have tried the mount fix and it worked (at least for me, could reproduce the issue by changing fstab to defaults). I'll extend the commit message a bit, but specify you as the author. I hope that is fine.

Compressing the backups is also a clever idea. I did some tests with other compression tools as well (all for libart.so with 3,860,745 bytes):

| Tool | Compression | Decompression | Size | Ratio |
| --- | --- | --- | --- | --- |
| gzip | 1.5 sec | 0.0 sec | 1,814,939 bytes | 47.0% |
| bzip2 | 1.45 sec | 0.5 sec | 1,790,548 bytes | 46.4% |
| lzop | 0.1 sec | 0.0 sec | 2,291,841 bytes | 59.3 % |
| xz -1 | 1.45 sec | 0.2 sec | 1,503,480 bytes | 38.9% |
| xz -3 | 1.7 sec | 0.2 sec | 1,421,840 bytes | 36.8% |
| xz -4 | 3.3 sec | 0.2 sec | 1,342,400 bytes | 34.8% |
| xz -9 | 4.0 sec | 0.2 sec | 1,331,968 bytes | 34.5% |

xz has clearly the best compression, and isn't slower on lowest compression level. For the other tools, compressing with -9 hardly makes any difference.

Using xz has a major catch though: BusyBox only includes decompression for it. So an additional (static?) binary would have to be shipped, which makes each flashable ZIP about 150 kB or so larger. We already save ~2 MB just for this one library with gzip or bzip2, which is pretty good. The additional ~400 kB would be nice, but I think that the effort is too high.

So it's about gzip vs. bzip2 then. The compressed size difference is just 24 kB, but gzip still seems to be used more often. Plus you're using it already. So I'll go for gzip as well.

I have to review and test your commands for compression though to make sure that it always leaves the system in a restorable state, no matter where it crashes. So I'll add gzip support now, but use it until I have thought it through completely. I'll also skip tar since I never published an installer with this and you version also was just out for a day.

**Comment by rovo89** [comment]
I also checked the memory impact of the GZIP_FAST option using `time -v`:

| GZIP_FAST | Time | Maximum resident set size (kbytes) |
| --- | --- | --- |
| 0 | 2.11 sec | 2160 |
| 1 | 1.66 sec | 2512 |
| 2 | 1.46 sec | 2512 |

So GZIP_FAST=2 gives us a speed-up of 30% with only 350 kB more memory usage.

**Comment by romracer** [comment]
No worries on modifying the commit.  I think I've got the 5.1 release to the point where I feel comfortable contributing back "upstream" so I started with this PR :)  Working with a few testers in the 5.1 thread also seemed to indicate the mount change helped them as well.

Have you ever over-engineered something?  That's what I did with tar :)  I'm not sure why I thought I needed to package them all up with their paths instead of just compressing in place, but whatever.  That's probably a product of working on this at work (where I'm an engineer) instead of being able to focus on it in free time.

As for the compression, its all but required in 5.1 I think.  Surely some devices, like my Moto X 2014, have 650+MB free on /system, but then others, like the incredibly popular N5, have about 11.8MB free.  If you install SuperSU, which I assume a lot of people using stock firmwares do, that's down to about 6MB free before installation which just isn't enough.

I did look at some of the compression alternatives but more or less came to the same conclusion you did.  LZO is fast, but not as good as gzip.  bzip2 is good and could have been a viable alternative, but in my professional work I tend to see it slower than gzip with minimal additional savings (unless its text, then its great but still slow).

xz (or LZMA2) would have been a great option because it compresses well and its fast.  That's probably why Linux distributions and the Linux kernel have adopted it so quickly.  But, alas, as you noted, busybox just doesn't include compression support for it.  The same is true of LZMA (think 7-zip) and busybox - decomp but no compression.  Since the solution with gzip left me with about 1.8MB on /system after installing Xposed and SuperSU on my N5, I came to the same conclusion and abandoned further work on LZMA2 for the time being.  Maybe its something that has to be revisited eventually, but I think in the near-term the additional complexity (another static binary, tool updates, etc) just doesn't add up.  Our energy is better spent solving other problems.

I hadn't really looked at the GZIP_FAST option so that is definitely a good find.  The comments in the busybox code say it may give slightly better compression too.  Since any device capable of running Android 5.0 (or 5.1) has at least 512MB of RAM, I'd think they should be able to spare an additional 350KB in recovery :P

I'd be happy to submit my updates to the installer/uninstaller in another PR.  If you wanted to look at my repo, romracer/XposedTools@3f123ba3 is probably the best place to start.  There's a couple commits on top of that I'd probably recommend too but you'll see them :)

**Comment by rovo89** [comment]
Yes, I have seen your commits. What I'm going to do is dropping the fallback to `/default.prop` entirely, and check whether `/system/build.prop` is accessible. Apart from that, I think it's mainly about the compressed backups, right?

**Comment by saihankhayhlaing** [comment]
#1

**Comment by saihankhayhlaing** [comment]
#1

**Pull request closed without merging**
